user_login_system/main/routes.py
from flask import Blueprint, render_template, request

from user_login_system.models import User

main = Blueprint('main', __name__)


# This is the home route
@main.route('/')
@main.route('/home')
def home():
    return render_template("home.html")


# This is the route to about page with all the users info i.e. non-deleted but approved and unapproved both
@main.route('/about')
def about():
    page = request.args.get('page', 1, type=int)
    users = User.query.filter(User.username != 'admin').paginate(per_page=5, page=page)
    admins = User.query.filter(User.username == 'admin')
    return render_template("about.html", title='About', users=users, admins=admins)

user_login_system/user/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user, logout_user, login_user

from user_login_system import bcrypt, db
from user_login_system.models import User
from user_login_system.user.forms import (RegisterationForm, LoginForm, UpdateAccountForm, AccountVerificationForm,
                                          RequestResetForm, ResetPasswordForm)
from user_login_system.user.utils import save_picture, send_reset_password_email

users = Blueprint('users', __name__)


# Route for a new user to register
@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterationForm()
    if form.validate_on_submit():
        print('form validated')
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'Registeration successful. You can login now.', 'success')
        return redirect(url_for('users.login'))
    # else:
    #     print('Validation failed! with errors: ', form.errors)
    return render_template('register.html', title='Register', form=form)


# Route for a registered user to login
@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        print('Form validation successful!!!')
        user = User.query.filter_by(email=form.email.data).first()
        if user.is_verified or not user.reviewed:
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                if user.reviewed:
                    flash(f'Login Successful. Welcome {user.username}', 'success')
                else:
                    flash(f'Login Successful. Welcome {user.username}. This account is still up for review.', 'success')
                next_page = request.args.get('next')
                if next_page:
                    if user.email == 'admin@demo.com':
                        return redirect(url_for('users.admin_panel'))
                    return redirect(url_for('users.user_dashboard'))
                else:
                    return redirect(url_for('main.home'))
            else:
                flash(f'Login Failed. Please check your email and password!', 'danger')
        else:
            flash('Login not possible. Your account has been disapproved by admin!', 'danger')
            return redirect(url_for('main.home'))
    # else:
    #     print('Validation failed!!!')
    #     print(form.errors)
    return render_template('login.html', title='Login', form=form)


# Route for a logged in user to logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# Route for admin to look into all the non-verified users
@users.route('/adminpanel', methods=['GET', 'POST'])
@login_required
def admin_panel():
    if current_user.username == 'admin':
        page = request.args.get('page', 1, type=int)
        users = User.query.filter(User.username != 'admin').filter(User.reviewed == False)\
            .paginate(per_page=5, page=page)
        # users = User.query.filter(User.username != 'admin').filter(User.reviewed == False).all()
        # admin profile pic
        profile_pic = url_for('static', filename='profile_pics/' + current_user.profile_pic)
        return render_template('admin_panel.html', title='Admin Panel', users=users, profile_pic=profile_pic)
    else:
        flash(f'You are not an admin. This page is not accessible to you.', 'danger')
        return redirect(url_for('users.user_dashboard'))


@users.route('/userdashboard', methods=['GET', 'POST'])
@login_required
def user_dashboard():
    if current_user.username != 'admin':
        form = UpdateAccountForm()
        if form.validate_on_submit():
            old_pic_data = current_user.profile_pic
            # old_path = os.path.join(app.root_path, 'static/profile_pics', old_pic_data)
            if form.profile_pic.data and not form.delete.data:
                pic_file = save_picture(form.profile_pic.data)
                current_user.profile_pic = pic_file
                # if old_pic_data != 'default.jpg':
                #     os.remove(old_path)

            if form.delete.data and current_user.profile_pic != 'default.jpg':
                # os.remove(old_path)
                current_user.profile_pic = 'default.jpg'
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            if form.delete.data and old_pic_data == 'default.jpg':
                flash(f'It will take all your might to delete this default profile image or just delete it directly '
                      f'from the folder that will do the trick.', 'success')
            else:
                flash('Your Account has been updated.', 'success')
            return redirect(url_for('users.user_dashboard'))
        elif request.method == 'GET':
            form.username.data = current_user.username
            form.email.data = current_user.email
        profile_pic = url_for('static', filename='profile_pics/' + current_user.profile_pic)
        return render_template('user_dashboard.html', title='User Dashboard', profile_pic=profile_pic, form=form)
    else:
        flash('You are an admin, act as one!', 'danger')
        return redirect(url_for('users.admin_panel'))


# This route will be used by admin to approve or delete users
@users.route('/userVerification/<string:username>', methods=['GET', 'POST'])
@login_required
def user_verification(username):
    user = User.query.filter(User.username == username).first()
    profile_pic = url_for('static', filename='profile_pics/' + user.profile_pic)
    if user.username != 'admin':
        form = AccountVerificationForm()
        if form.is_submitted():
            if form.delete.data:
                # delete account
                db.session.delete(user)
                flash('User account has been deleted!', 'success')
            else:
                if form.verify.data:
                    # set verify to True
                    user.is_verified = True
                user.reviewed = True
                flash(f'User Verification process for {user.username} finished.', 'success')
            db.session.commit()
            return redirect(url_for('users.admin_panel'))
        # else:
        #     print(f'\nForm Errors: {form.errors}\n')
        return render_template('user_verification.html', title='User Verification', form=form, user=user,
                               profile_pic=profile_pic)
    else:
        return redirect(url_for('main.home'))


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_password_email(user)
        flash('Please check your email for instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This token is either invalid or has expired!!!', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated. Please login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset Password', form=form)

user_login_system/templates/about.html
{% extends "layout.html" %}
{% block bodycontent %}
    <h1>User Login System About Page</h1>
    <h2>Administrators</h2>
    {% for admin in admins %}
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img"
                     src="{{ url_for('static', filename='profile_pics/' + admin.profile_pic) }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ admin.username }}</h2>
                    <h5 class="text-secondary">{{ admin.email }}</h5>
                </div>
            </div>
        </div>
    {% endfor %}
    <h2>Users</h2>
    {% for user in users.items %}
        {% if user.username != 'admin' %}
            <div class="content-section">
                <div class="media">
                    <img class="rounded-circle account-img"
                         src="{{ url_for('static', filename='profile_pics/' + user.profile_pic) }}">
                    <div class="media-body">
                        <h2 class="account-heading">{{ user.username }}</h2>
                        <h5 class="text-secondary">{{ user.email }}</h5>
                        {% if user.is_verified %}
                            <h5 class="text-secondary">Account verified</h5>
                        {% endif %}
                        {% if user.reviewed and not user.is_verified %}
                            <h5 class="text-secondary">Account not verified</h5>
                        {% endif %}
                        {% if not user.reviewed %}
                            <h5 class="text-secondary">Account under Review</h5>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% for page_number in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_number %}
            {% if users.page == page_number %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for('main.about', page=page_number) }}">{{ page_number }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.about', page=page_number) }}">
                    {{ page_number }}
                </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock bodycontent %}

user_login_system/templates/admin_panel.html
{% extends "layout.html" %}
{% block bodycontent %}
    <h1>Users List</h1>
    {% for user in users.items %}
        {% if user.username != 'admin' %}
            <div class="content-section">
                <div class="media">
                    <img class="rounded-circle account-img"
                         src="{{ url_for('static', filename='profile_pics/' + user.profile_pic) }}">
                    <div class="media-body">
                        <h3 class="account-heading">Username:
                            <a href="{{ url_for('users.user_verification', username=user.username) }}">
                                {{ user.username }}</a>
                            </h3>
                        <h4 class="text-secondary">Email: {{ user.email }}</h4>
                        <h4 class="text-secondary">Registration:
                            {{ current_user.date_of_registration.strftime("%B %d, %Y") }}</h4>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% for page_number in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_number %}
            {% if users.page == page_number %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for('users.admin_panel', page=page_number) }}">{{ page_number }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('users.admin_panel', page=page_number) }}">{{ page_number }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock bodycontent %}
{% block sidebar %}
    <div class="col-md-4">
        <div class="content-section">
            <h3>Admin Info</h3>
            <div>
                <div class="content-section">
                    <div class="media">
                        <img class="rounded-circle account-img" src="{{ profile_pic }}">
                        <div class="media-body">
                            <h2 class="account-heading">{{ current_user.username }}</h2>
                            <h5 class="text-secondary">{{ current_user.email }}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock sidebar %}

user_login_system/templates/home.html
{% extends "layout.html" %}
{% block bodycontent %}
    <div class="mb-4">
        <h3 class="text-muted mb-4">This is a simple user login app with features like registeration, login,
            logout, change password, change profile pic etc. with an admin overseeing everything and having
            the ablity to delete and approve any user anytime.
        </h3>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('main.home') }}">Home:</a></h2>
        <h5 class="text-muted">This is the Home Page. So this is the overview/summary of this app. Focus, of
            this app is not on the design but on the backend (flask, python etc.) part of development.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('main.about') }}">About:</a></h2>
        <h5 class="text-muted">About Page contains "paginated" list of all the users.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('users.register') }}">Register:</a></h2>
        <h5 class="text-muted">Register Page is a form for new users to register using a unique email.
            Along with a link to go to login page if the user is already registered.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('users.login') }}">Login:</a></h2>
        <h5 class="text-muted">Login Page is also a form for user to login. It also contains a link to
            reset password in case the user forgot his/her password (an email is sent to the registered
            email id for the user to click and change password) and a link to register in case
            the user is not a registered user.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('users.admin_panel') }}">Admin Panel:</a></h2>
        <h5 class="text-muted">Admin Panel page is the page which only the admin can access but only
            after logging in. Here the admin can checkout non-verified users and can approve, disapprove
            and delete them. It also displays basic admin info as well.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2"><a href="{{ url_for('users.user_dashboard') }}">User Dashboard:</a></h2>
        <h5 class="text-muted">User Dashboard shows all the info of a particular user and also contains
            a form for user to update his/her account info.</h5>
    </div>
    <div class="mb-4">
        <h2 class="mb-2">Other Pages:</h2>
        <h5 class="text-muted">Other Pages like for resetting password etc. only come into play when
            a user has their need to.</h5>
    </div>
{% endblock bodycontent %}

user_login_system/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity=
            "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>ULS - {{ title }}</title>
    {% else %}
        <title>User Login System</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">User Login System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                  aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if current_user.email == 'admin@demo.com' %}
                  <a class="nav-item nav-link" href="{{ url_for('users.admin_panel') }}">Admin Panel</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.user_dashboard') }}">User Dashboard</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          {% block bodycontent %}{% endblock bodycontent %}
        </div>
        {% block sidebar %}{% endblock sidebar %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/
    rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-
    ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-
    JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

user_login_system/templates/login.html
{% extends "layout.html" %}
{% block bodycontent %}
    <div class="content-section">
        <form method="POST" action="{{ url_for('users.login') }}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock bodycontent %}

user_login_system/templates/register.html
{% extends "layout.html" %}
{% block bodycontent %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock bodycontent %}

user_login_system/templates/reset_password.html
{% extends "layout.html" %}
{% block bodycontent %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock bodycontent %}

user_login_system/templates/reset_request.html
{% extends "layout.html" %}
{% block bodycontent %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock bodycontent %}

user_login_system/templates/user_verification.html
{% extends "layout.html" %}
{% block bodycontent %}
    <h1>User Verification</h1>
    <div>
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ profile_pic }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <h5 class="text-secondary">{{ user.email }}</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="content-section">
        <form method="POST" action="{{ url_for('users.user_verification', username=user.username) }}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">User Verification</legend>
                <div class="form-check">
                    {{ form.verify(class="form-check-input") }}
                    {{ form.verify.label(class="form-check-label") }}
                </div>
                <div class="form-check">
                    {{ form.delete(class="form-check-input") }}
                    {{ form.delete.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock bodycontent %}